### ISSUE TITLE
vampire-coast-ranged-units-not-getting-firerate-reduced-reload-from-veterancy

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#57]
https://forums.totalwar.com/discussion/267362/vampire-coast-ranged-units-not-getting-firerate-reduced-reload-from-veterancy#latest

**Comment by sm0kin** [comment]
All vampire coast ranged units gain firerate from chevrons. The report is slightly suspicious considering his rank 0 "Zombie Pirate Gunnery Mob (Handguns)" has the same ranged dps as mine at rank9. The unit's other stats are also definitely not vanilla (9000hp vs 6480hp and way too high melee atk/def values).
I bet this was caused by a mod.
