### ISSUE TITLE
Norscan God champions seem to have no faction AI. They just stand in one place (hopefully it's intentional)

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#65]

**Comment by sm0kin** [comment]
The Norscan God champions factions are basically script controlled and spawned rebel factions. The invasion manager gives them a target to chase after, in this case the norsca faction leader and that's all they do. If they don't have a target they stand around.
They aren't real factions so I guess this is intentional.
