### ISSUE TITLE
Monument of Grimnir doesn't unlock Grombrindal, reports of other lords not being unlocked too

### ISSUE THREAD

**Issue by Harmandodelavega** [chadvandy/community_bugfix_mod#66]

**Comment by sm0kin** [comment]
Can't reproduce this issue. Building the "Monument of Grimnir" unlocked Grombrindal in my tests.

The legendary lord unlock script did not change at all for more than a year. I think these reports stem from,
1: People not really reading/comprehending what the unlock condition is. E.g. a lot of people argue they built the "Monument of Grimnir" when they actually got it via confederation or conquest.
2: Most people don't know that all locked legendary lords are unlocked for the AI at turn 30. The AI doesn't have to fullfill the unlock condition at all. And even when the AI reaches turn 30, they might not recruit the legendary lord immediately due to missing funds or the ai doesn't want to raise a new army or it decides to not replace a existing lord because he's deemed stronger than the legendary lord (e.g. higher level).
 -> You can't get a locked legendary lord if you confederate its faction before the lord was recruited (min turn 30).
3: A LOT of people play with outdated script mods in the first few weeks after a dlc release and that can cause the LL unlock scripts to break.

**Comment by Harmandodelavega** [comment]
This is happening with Volkmar too apparently and the guy explicitly said he built more of those monuments I would keep it up for now

**Comment by sm0kin** [comment]
moved to trello
